= PWM RAMP library for Arduino =

This library is designed to generate PWM signals where changes in the duty cycle value has no direct effect on the output but are slowly changed using a ramp. The ramp time defines the time in ms for a change from the two extremes. The update method changes the signal and the cycle time can be set at creation.

For more information about this library please visit us at
http://nibble-arts.org

== License ==

Copyright (c) Nibble-arts. All right reserved.
Copyright (c) Thomas Winkler. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA